In [1]:
from pandasDB import DataBase

In [2]:
db = DataBase()

In [4]:
results = db.query('food', False)
# a = results['track_data']
# a['song_title']
data = results['track_data']

In [12]:
firstSong = data[0]
firstSong['X'][['mfcc', 'spectral_contrast']]

feature         mfcc                                                    \
statistics  kurtosis
number            01        02        03        04        05        06
track_id
2           3.856789  1.541901  0.000816  0.330728  0.118731 -0.342687

feature                                             ... spectral_contrast  \
statistics                                          ...              skew
number            07        08        09        10  ...                05
track_id                                            ...
2          -0.259252  0.146735  0.410656 -0.162872  ...           0.43285

feature                                                               \
statistics                         std
number            06      07        01        02        03        04
track_id
2           1.690805 -1.5719  4.541557  4.321756  3.936234  3.144537

feature
statistics
number            05        06        07
track_id
2           3.310087  3.096597  7.622641

[1 rows x 189 columns]

In [39]:
results['features']

feature    chroma_cens                                                    \
statistics    kurtosis
number              01        02        03        04        05        06
track_id
148133       -0.212858 -0.931763  0.670636 -0.215534 -0.827843 -0.786714

feature                                           ...   tonnetz            \
statistics                                        ...       std
number            07      08        09        10  ...        04        05
track_id                                          ...
148133     -1.051842 -0.6591 -1.254777 -0.951957  ...  0.143602  0.027572

feature                     zcr                                          \
statistics             kurtosis       max      mean    median       min
number            06         01        01        01        01        01
track_id
148133      0.026145  16.074034  0.672852  0.073851  0.056152  0.001953

feature
statistics      skew       std
number            01        01
track_id
148133      2.973313  0.062099

[1 rows x 518 columns]